image: { repository: us-docker.pkg.dev/factorymind/services/mes-bff }
serviceAccount: { annotations: { iam.gke.io/gcp-service-account: mes-bff@factorymind.iam.gserviceaccount.com } }
nodeSelector: { topology.kubernetes.io/region: us-central1 }
