apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: factorymind-gcp
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/prabhat-roy/FactoryMind.git
        revision: HEAD
        directories:
          - path: helm/charts/*
  template:
    metadata:
      name: '{{path.basename}}-gcp'
      labels:
        cloud: gcp
        factorymind.io/managed-by: argocd
    spec:
      project: factorymind
      source:
        repoURL: https://github.com/prabhat-roy/FactoryMind.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
            - values-gcp.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: factorymind
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true