apiVersion: v1
kind: Service
metadata:
  name: {{ include "svc.fullname" . }}
  labels: {{- include "svc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - { name: http, port: {{ .Values.service.port }}, targetPort: http }
    - { name: metrics, port: {{ .Values.service.metricsPort }}, targetPort: metrics }
  selector: {{- include "svc.selectorLabels" . | nindent 4 }}
